<?php

define('SHOW_STATUS',0);
define('GOOD_RESULT',1);
define('HIDE_STATUS',2);
define('EXACT_SCORE',3);

/* CODE ERROR */
define('FORGOT_PASSWORD_OK',-1);
define('USER_UNKNOWN',-2);
define('PASSWORD_MISMATCH',-3);
define('INCORRECT_PASSWORD',-4);
define('CHANGE_PASSWORD_OK',-5);
define('GROUP_ALREADY_EXISTS',-6);
define('CREATE_GROUP_OK',-7);
define('JOIN_GROUP_FORBIDDEN',-8);
define('JOIN_GROUP_OK',-9);
define('INCORRECT_EMAIL',-10);
define('LOGIN_ALREADY_EXISTS',-11);
define('FIELDS_EMPTY',-12);
define('REGISTER_OK',-13);
define('INVITE_WITHOUT_GROUP',-14);
define('SEND_INVITATIONS_OK',-15);
define('SEND_INVITATIONS_ERROR',-16);
define('AWL_NOT_GOOD_SITE',-17);
define('LDAP_CONNECT_ERROR',-18);
define('LDAP_BIND_ERROR',-19);
define('JOIN_GROUP_FULL',-20);
define('CHANGE_ACCOUNT_OK',-21);
define('EMAIL_ALREADY_EXISTS',-22);
define('FORGOT_LOGIN_OK',-23);
define('USERNAME_ALREADY_EXISTS',-24);

define('UNKNOWN_ERROR',-99);
