<?php
define('SHOW_STATUS', 0);
define('GOOD_RESULT', 1);
define('HIDE_STATUS', 2);
define('EXACT_SCORE', 3);

/* CODE ERROR */
define('FORGOT_IDS_OK',-1);
define('USER_UNKNOWN',-2);
define('PASSWORD_MISMATCH',-3);
define('INCORRECT_PASSWORD',-4);
define('CHANGE_PASSWORD_OK',-5);
define('EMAIL_UNKNOWN',-6);
define('FORGOT_IDS_KO',-7);
define('GROUP_ALREADY_EXISTS',-8);
define('CREATE_GROUP_OK',-9);
define('INCORRECT_EMAIL',-10);
define('LOGIN_ALREADY_EXISTS',-11);
define('FIELDS_EMPTY',-12);
define('REGISTER_OK',-13);
define('JOIN_GROUP_OK', -14);
define('JOIN_GROUP_FORBIDDEN', -15);
define('INVITE_WITHOUT_GROUP',-17);
define('SEND_INVITATIONS_OK',-18);
define('SEND_INVITATIONS_ERROR',-19);
define('CHANGE_ACCOUNT_OK',-21);
define('EMAIL_ALREADY_EXISTS',-22);
define('USERNAME_ALREADY_EXISTS',-24);
define('GROUP_UNKNOWN',-25);
define('INCORRECT_CREDENTIALS',-26);
define('UNKNOWN_ERROR',-99);
